### PR TITLE
v1.0

### PR DESCRIPTION
**Pull request by WSJI0**
1.0 release

### CODE REVIEW

**Comment by WSJI0** [comment]
v1.0

**Review by SeolJiyun — APPROVED** [review]
최종 확인_지윤

**Review by suno-boy — COMMENTED** [review]
ㅁㄴㅇㄻㄴㅇㄹ

**Review by scc9811 — APPROVED** [review]

**Review by wltn2411 — APPROVED** [review]

**Comment by wltn2411** [comment]
,,

**Comment by wltn2411** [comment]
,,

**Review by wltn2411 — APPROVED** [review]
ㅇㅇ

**Review by suno-boy — APPROVED** [review]

**Pull request merged**
